version: '3.1'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: pocspringpostgresql:latest
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - PostgreSQL
        # condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    networks:
      - spring-network
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./src/main/resources/script/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-network:
    driver: bridge