spec:
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgresql
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20